clc;
G=imread ('monkey.jpg');
subplot (2,3,1);
imshow (G) ;
title('First Image');
Y=imread('images.jpg'); 
subplot (2,3,2);
imshow (Y) ;
title ('Second Image'); 
J=imadd (G, 50);
subplot (2,3,3);
imshow (J);
title('Add Image'); S=imsubtract (G, 50);
subplot (2, 3, 4);
imshow (S);
title('Subtract Image');
IM=immultiply (G, 2);
subplot (2,3,5);
imshow (IM) ;
title ('Multiply Image');
Z=imfuse(G,Y);
subplot(2,3,6);
imshow(Z);
title('Fused Image');