I=imread('monkey.jpg');
G=rgb2gray(I);
subplot(2,3,1);
imshow(G);
title('GreyScale Image');
BW1 = edge(G,'Canny');
BW2 = edge(G,'Prewitt');
BW3 = edge(G,'Sobel');
BW4 = edge(G,'Roberts');
subplot(2,3,2);
imshow(BW1);
title('Canny Image');
subplot(2,3,3);
imshow(BW2);
title('Prewitt Image');
subplot(2,3,4);
imshow(BW3);
title('Sobelt Image');
subplot(2,3,5);
imshow(BW4);
title('Roberts Image');
% b=edge(G);
% subplot(2,3,6);
% imshow(b);    