I=imread('coin.jpg');
subplot(2,2,1);
imshow(I);
title('originl image 1');
Se=strel('disk',5);
BW1=imopen(I,Se);
subplot(2,2,2);
imshow(BW1);
title('open image');
subplot(2,2,3);
imshow(I);
title('original image 2');
BW2=imclose(I,Se);
subplot(2,2,4);
imshow(BW2);
title('close image');