#Write a function nearly equal to test whether the two strings are nearly equal.Two strings are nearly equal when a can be generated by a single mutation on

string1 = input("Enter first string: ")

string2 = input("Enter second string: ")

if string1 == string2:

    print("\nBoth strings are equal to each other.")

    print(string1,"==",string2);

else:

    print("\nStrings are not equal.")

    print(string1,"!=",string2); 